# Generated by Django 5.1.7 on 2025-03-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_drf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
